Fix: #issue76161: error C2440 of 'static_cast': cannot convert from 'InType' to 'OutType' (#76185)
* fix error C2440 when running ninja on windows

* fix pre-commit codestyle issues